Rest of the windmill tests

diff --git a/ideaList/windmill_tests/run b/ideaList/windmill_tests/run
--- a/ideaList/windmill_tests/run
+++ b/ideaList/windmill_tests/run
@@ -4,14 +4,12 @@ TESTDIR=$(dirname "$(pwd)/$0")
 
 if [ $# = 1 ]; then
   TEST="$1"
-else
-  TEST="$TESTDIR"
+  if ! [ -e "$TEST" ]; then
+    echo "Could not find test $TEST"
+    exit 1
+  fi
 fi
 
-if ! [ -e "$TEST" ]; then
-  echo "Could not find test $TEST"
-  exit 1
-fi
 
 MANAGEDIR="$TESTDIR"
 while ! [ -e "$MANAGEDIR/manage.py" ] && [ "$MANAGEDIR" != "/" ]; do
@@ -23,9 +21,36 @@ if ! [ -e "$MANAGE" ]; then
   exit 1
 fi
 
-python $MANAGE testserver --addrport 8123 "$MANAGEDIR/ideaList/fixtures/auth.json" "$MANAGEDIR/ideaList/fixtures/itemfrequencies.yaml" &
-TESTSERVER_PID=$!
-sleep 5 # give the server some time to start
+TESTSERVER_PID=""
 
-windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TEST"
-kill $TESTSERVER_PID
+function run_testserver {
+  python $MANAGE testserver --addrport 8123 "$MANAGEDIR/ideaList/fixtures/auth.json" "$MANAGEDIR/ideaList/fixtures/itemfrequencies.yaml" &
+  TESTSERVER_PID=$!
+  sleep 5 # give the server some time to start
+}
+
+function kill_testserver {
+  if [ -n $TESTSERVER_PID ]; then
+    kill $TESTSERVER_PID
+  fi
+  TESTSERVER_PID=""
+}
+
+
+
+
+if [ -n "$TEST" ]; then
+  run_testserver
+  windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TEST"
+  kill_testserver
+else
+  # TODO: recursively iterate through all subdirectories of $TESTDIR with __init__.py
+
+  run_testserver
+  windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TESTDIR"
+  kill_testserver
+
+  run_testserver
+  windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TESTDIR/with_items"
+  kill_testserver
+fi
